apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
data:
  data.js: |
    db = db.getSiblingDB('product-service-db');
    db.createCollection('products');
    db.products.insertMany([
      { name: "Refrigerator", price: 100 },
      { name: "Washing Machine", price: 200 },
      { name: "Microwave Oven", price: 150 }
    ]);
